//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputMaps/ArcadeBoxInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ArcadeBoxInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ArcadeBoxInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ArcadeBoxInputs"",
    ""maps"": [
        {
            ""name"": ""ArcadeControls"",
            ""id"": ""a2e591dd-5820-4f1b-abc4-26a6c8326f7a"",
            ""actions"": [
                {
                    ""name"": ""MenuBtn1"",
                    ""type"": ""Button"",
                    ""id"": ""3666222b-abe8-4e86-b212-dbd10f63fcc1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuBtn2"",
                    ""type"": ""Button"",
                    ""id"": ""54f975b9-c15a-4bbb-8333-1e4c06a1934f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuBtn3"",
                    ""type"": ""Button"",
                    ""id"": ""58c38674-e485-48cb-8c63-ef2b7d9300b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuBtn4"",
                    ""type"": ""Button"",
                    ""id"": ""a5f11b1b-5768-40b5-9184-fc23b04f7b34"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P1Btn1"",
                    ""type"": ""Button"",
                    ""id"": ""464d947e-8c53-4cb1-b932-53263b85f67f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P1Btn2"",
                    ""type"": ""Button"",
                    ""id"": ""644ceedd-4efa-4f74-9a67-cbfe3c6b3c63"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P1Btn3"",
                    ""type"": ""Button"",
                    ""id"": ""f8f616e1-c185-4940-ac0d-35f4b2a4f7d4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P1Btn4"",
                    ""type"": ""Button"",
                    ""id"": ""ba8c6683-386b-49ba-9302-7041dbec2e23"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P1Btn5"",
                    ""type"": ""Button"",
                    ""id"": ""1dcd865f-9cb3-4128-81bb-a794589b8bbd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P1Btn6"",
                    ""type"": ""Button"",
                    ""id"": ""9e36799a-6a97-43f6-a74f-7cf403711edc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P1JoyStick"",
                    ""type"": ""Value"",
                    ""id"": ""b1988850-013c-489f-acdd-10f4c0e34664"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""09049dc2-e0cc-4c99-81ca-28ef2e81f400"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuBtn1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""601b67bc-d6d4-4b65-9f49-4a3584c27cd1"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuBtn2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1e31347-daad-4f94-bdfd-ca5d935ccb69"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuBtn3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""898f4134-0feb-4fea-b67a-da117d64ccc5"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuBtn4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fed7646c-3418-43f5-ba2c-732e711100da"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button12"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Btn1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d10a9b6d-8001-4677-af5b-c67ef9f9e033"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button10"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Btn2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9ce7fc3-27e1-4a18-bc34-9815c36198c2"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Btn3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32b266ab-d41c-45e5-9a83-e9d2677d4b77"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button11"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Btn4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3debe19-c915-4722-866d-7d5c679556c6"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Btn5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c3d3056-cd4b-418e-80db-46b203040d70"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Btn6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e3f230f-d4d2-4897-8ee4-d7bdef7ec17d"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1JoyStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ArcadeControls
        m_ArcadeControls = asset.FindActionMap("ArcadeControls", throwIfNotFound: true);
        m_ArcadeControls_MenuBtn1 = m_ArcadeControls.FindAction("MenuBtn1", throwIfNotFound: true);
        m_ArcadeControls_MenuBtn2 = m_ArcadeControls.FindAction("MenuBtn2", throwIfNotFound: true);
        m_ArcadeControls_MenuBtn3 = m_ArcadeControls.FindAction("MenuBtn3", throwIfNotFound: true);
        m_ArcadeControls_MenuBtn4 = m_ArcadeControls.FindAction("MenuBtn4", throwIfNotFound: true);
        m_ArcadeControls_P1Btn1 = m_ArcadeControls.FindAction("P1Btn1", throwIfNotFound: true);
        m_ArcadeControls_P1Btn2 = m_ArcadeControls.FindAction("P1Btn2", throwIfNotFound: true);
        m_ArcadeControls_P1Btn3 = m_ArcadeControls.FindAction("P1Btn3", throwIfNotFound: true);
        m_ArcadeControls_P1Btn4 = m_ArcadeControls.FindAction("P1Btn4", throwIfNotFound: true);
        m_ArcadeControls_P1Btn5 = m_ArcadeControls.FindAction("P1Btn5", throwIfNotFound: true);
        m_ArcadeControls_P1Btn6 = m_ArcadeControls.FindAction("P1Btn6", throwIfNotFound: true);
        m_ArcadeControls_P1JoyStick = m_ArcadeControls.FindAction("P1JoyStick", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ArcadeControls
    private readonly InputActionMap m_ArcadeControls;
    private List<IArcadeControlsActions> m_ArcadeControlsActionsCallbackInterfaces = new List<IArcadeControlsActions>();
    private readonly InputAction m_ArcadeControls_MenuBtn1;
    private readonly InputAction m_ArcadeControls_MenuBtn2;
    private readonly InputAction m_ArcadeControls_MenuBtn3;
    private readonly InputAction m_ArcadeControls_MenuBtn4;
    private readonly InputAction m_ArcadeControls_P1Btn1;
    private readonly InputAction m_ArcadeControls_P1Btn2;
    private readonly InputAction m_ArcadeControls_P1Btn3;
    private readonly InputAction m_ArcadeControls_P1Btn4;
    private readonly InputAction m_ArcadeControls_P1Btn5;
    private readonly InputAction m_ArcadeControls_P1Btn6;
    private readonly InputAction m_ArcadeControls_P1JoyStick;
    public struct ArcadeControlsActions
    {
        private @ArcadeBoxInputs m_Wrapper;
        public ArcadeControlsActions(@ArcadeBoxInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @MenuBtn1 => m_Wrapper.m_ArcadeControls_MenuBtn1;
        public InputAction @MenuBtn2 => m_Wrapper.m_ArcadeControls_MenuBtn2;
        public InputAction @MenuBtn3 => m_Wrapper.m_ArcadeControls_MenuBtn3;
        public InputAction @MenuBtn4 => m_Wrapper.m_ArcadeControls_MenuBtn4;
        public InputAction @P1Btn1 => m_Wrapper.m_ArcadeControls_P1Btn1;
        public InputAction @P1Btn2 => m_Wrapper.m_ArcadeControls_P1Btn2;
        public InputAction @P1Btn3 => m_Wrapper.m_ArcadeControls_P1Btn3;
        public InputAction @P1Btn4 => m_Wrapper.m_ArcadeControls_P1Btn4;
        public InputAction @P1Btn5 => m_Wrapper.m_ArcadeControls_P1Btn5;
        public InputAction @P1Btn6 => m_Wrapper.m_ArcadeControls_P1Btn6;
        public InputAction @P1JoyStick => m_Wrapper.m_ArcadeControls_P1JoyStick;
        public InputActionMap Get() { return m_Wrapper.m_ArcadeControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ArcadeControlsActions set) { return set.Get(); }
        public void AddCallbacks(IArcadeControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_ArcadeControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ArcadeControlsActionsCallbackInterfaces.Add(instance);
            @MenuBtn1.started += instance.OnMenuBtn1;
            @MenuBtn1.performed += instance.OnMenuBtn1;
            @MenuBtn1.canceled += instance.OnMenuBtn1;
            @MenuBtn2.started += instance.OnMenuBtn2;
            @MenuBtn2.performed += instance.OnMenuBtn2;
            @MenuBtn2.canceled += instance.OnMenuBtn2;
            @MenuBtn3.started += instance.OnMenuBtn3;
            @MenuBtn3.performed += instance.OnMenuBtn3;
            @MenuBtn3.canceled += instance.OnMenuBtn3;
            @MenuBtn4.started += instance.OnMenuBtn4;
            @MenuBtn4.performed += instance.OnMenuBtn4;
            @MenuBtn4.canceled += instance.OnMenuBtn4;
            @P1Btn1.started += instance.OnP1Btn1;
            @P1Btn1.performed += instance.OnP1Btn1;
            @P1Btn1.canceled += instance.OnP1Btn1;
            @P1Btn2.started += instance.OnP1Btn2;
            @P1Btn2.performed += instance.OnP1Btn2;
            @P1Btn2.canceled += instance.OnP1Btn2;
            @P1Btn3.started += instance.OnP1Btn3;
            @P1Btn3.performed += instance.OnP1Btn3;
            @P1Btn3.canceled += instance.OnP1Btn3;
            @P1Btn4.started += instance.OnP1Btn4;
            @P1Btn4.performed += instance.OnP1Btn4;
            @P1Btn4.canceled += instance.OnP1Btn4;
            @P1Btn5.started += instance.OnP1Btn5;
            @P1Btn5.performed += instance.OnP1Btn5;
            @P1Btn5.canceled += instance.OnP1Btn5;
            @P1Btn6.started += instance.OnP1Btn6;
            @P1Btn6.performed += instance.OnP1Btn6;
            @P1Btn6.canceled += instance.OnP1Btn6;
            @P1JoyStick.started += instance.OnP1JoyStick;
            @P1JoyStick.performed += instance.OnP1JoyStick;
            @P1JoyStick.canceled += instance.OnP1JoyStick;
        }

        private void UnregisterCallbacks(IArcadeControlsActions instance)
        {
            @MenuBtn1.started -= instance.OnMenuBtn1;
            @MenuBtn1.performed -= instance.OnMenuBtn1;
            @MenuBtn1.canceled -= instance.OnMenuBtn1;
            @MenuBtn2.started -= instance.OnMenuBtn2;
            @MenuBtn2.performed -= instance.OnMenuBtn2;
            @MenuBtn2.canceled -= instance.OnMenuBtn2;
            @MenuBtn3.started -= instance.OnMenuBtn3;
            @MenuBtn3.performed -= instance.OnMenuBtn3;
            @MenuBtn3.canceled -= instance.OnMenuBtn3;
            @MenuBtn4.started -= instance.OnMenuBtn4;
            @MenuBtn4.performed -= instance.OnMenuBtn4;
            @MenuBtn4.canceled -= instance.OnMenuBtn4;
            @P1Btn1.started -= instance.OnP1Btn1;
            @P1Btn1.performed -= instance.OnP1Btn1;
            @P1Btn1.canceled -= instance.OnP1Btn1;
            @P1Btn2.started -= instance.OnP1Btn2;
            @P1Btn2.performed -= instance.OnP1Btn2;
            @P1Btn2.canceled -= instance.OnP1Btn2;
            @P1Btn3.started -= instance.OnP1Btn3;
            @P1Btn3.performed -= instance.OnP1Btn3;
            @P1Btn3.canceled -= instance.OnP1Btn3;
            @P1Btn4.started -= instance.OnP1Btn4;
            @P1Btn4.performed -= instance.OnP1Btn4;
            @P1Btn4.canceled -= instance.OnP1Btn4;
            @P1Btn5.started -= instance.OnP1Btn5;
            @P1Btn5.performed -= instance.OnP1Btn5;
            @P1Btn5.canceled -= instance.OnP1Btn5;
            @P1Btn6.started -= instance.OnP1Btn6;
            @P1Btn6.performed -= instance.OnP1Btn6;
            @P1Btn6.canceled -= instance.OnP1Btn6;
            @P1JoyStick.started -= instance.OnP1JoyStick;
            @P1JoyStick.performed -= instance.OnP1JoyStick;
            @P1JoyStick.canceled -= instance.OnP1JoyStick;
        }

        public void RemoveCallbacks(IArcadeControlsActions instance)
        {
            if (m_Wrapper.m_ArcadeControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IArcadeControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_ArcadeControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ArcadeControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ArcadeControlsActions @ArcadeControls => new ArcadeControlsActions(this);
    public interface IArcadeControlsActions
    {
        void OnMenuBtn1(InputAction.CallbackContext context);
        void OnMenuBtn2(InputAction.CallbackContext context);
        void OnMenuBtn3(InputAction.CallbackContext context);
        void OnMenuBtn4(InputAction.CallbackContext context);
        void OnP1Btn1(InputAction.CallbackContext context);
        void OnP1Btn2(InputAction.CallbackContext context);
        void OnP1Btn3(InputAction.CallbackContext context);
        void OnP1Btn4(InputAction.CallbackContext context);
        void OnP1Btn5(InputAction.CallbackContext context);
        void OnP1Btn6(InputAction.CallbackContext context);
        void OnP1JoyStick(InputAction.CallbackContext context);
    }
}
